name: Online Reservierung Auth Java CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WAR_PATH: target/or-auth.war

jobs:
  # --- STAGE 1: BUILD & TEST ---
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        uses: s4u/setup-maven-action@v1.20.0
        with:
          java-version: '24'
          maven-version: '3.9.9'
          args: clean package -DskipTests

      #- name: Run Unit Tests
      #  run: mvn test

      - name: Upload Artifact (WAR)
        uses: actions/upload-artifact@v6
        with:
          name: or-auth-war
          path: ${{ env.WAR_PATH }}

  # --- STAGE 2: DOCKER BUILD & PUSH ---
  docker:
    needs: build
    runs-on: arc-runner-set

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: or-auth-war
          path: auth-service/target/

      - name: Build Docker Image
        run: docker build -t auth-service:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
