name: Online Reservierung Auth Java CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WAR_PATH: target/or-auth.war

jobs:
  # --- STAGE 1: BUILD & TEST ---
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        uses: s4u/setup-maven-action@v3.9.14
        with:
          java-version: '24'
          maven-version: '3.9.9'
          args: clean package -DskipTests

      #- name: Run Unit Tests
      #  run: mvn test

      - name: Upload Artifact (WAR)
        uses: actions/upload-artifact@v6
        with:
          name: or-auth-war
          path: ${{ env.WAR_PATH }}

  # --- STAGE 2: DOCKER BUILD & PUSH ---
  docker:
    needs: build
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: dipag-war
          path: target/

      - name: Log in to Registry
        uses: docker/login-action@v6
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Das Dockerfile sollte das WAR-File in /usr/local/tomcat/webapps/ kopieren
